# Generated by Django 4.2.3 on 2023-11-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_tasks',
            old_name='employee',
            new_name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='my_tasks',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='my_tasks',
            name='client',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_tasks',
            name='progress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='my_tasks',
            name='comments',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_tasks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.projects'),
        ),
    ]
