# Generated by Django 4.2.3 on 2023-11-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_employee_my_tasks_assigned_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_tasks',
            old_name='assigned_employee',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='my_tasks',
            name='client',
        ),
        migrations.RemoveField(
            model_name='my_tasks',
            name='progress',
        ),
        migrations.AddField(
            model_name='my_tasks',
            name='assign_to',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_tasks',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='my_tasks',
            name='project',
            field=models.CharField(max_length=100),
        ),
    ]
