# Generated by Django 4.2.3 on 2023-11-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_employee_my_tasks_assigned_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_tasks',
            name='client',
        ),
    ]
