# Generated by Django 4.2.3 on 2023-12-12 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_tickets_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='employee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
