# Generated by Django 4.2.3 on 2023-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_tickets_employee_alter_tickets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='approved_by',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='comments',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
