# Generated by Django 4.2.3 on 2023-12-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
