# Generated by Django 4.2.3 on 2023-12-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_expenses_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='approved_by',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='comments',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
