# Generated by Django 4.2.3 on 2023-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_expenses_approved_by_expenses_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='priority',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
