# Generated by Django 4.2.3 on 2023-12-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_tickets_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
