# Generated by Django 4.2.3 on 2023-12-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_rename_rbi_data_rbi_data_import'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rbi_Data_Import',
        ),
    ]
