# Generated by Django 4.2.3 on 2023-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_rbi_data_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
