# Generated by Django 4.2.3 on 2023-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0024_bank_account_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='is_active',
            field=models.CharField(max_length=100),
        ),
    ]
