# Generated by Django 4.2.3 on 2023-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0025_alter_bank_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
