# Generated by Django 4.2.3 on 2023-12-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0027_alter_expenses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_salary',
            name='month_year',
            field=models.CharField(max_length=100),
        ),
    ]
