# Generated by Django 4.2.3 on 2023-12-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0028_alter_basic_salary_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
            ],
        ),
    ]
