# Generated by Django 4.2.3 on 2023-12-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_year',
            name='financial_year',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
