# Generated by Django 4.2.3 on 2023-12-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_customuser_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fullname',
        ),
    ]
